FROM ismaelfaro/qiskit:0.23.0

RUN pip install jupyterlab  
RUN git clone https://github.com/Qiskit/qiskit-tutorials.git

RUN echo -e "jupyter lab --allow-root --no-browser --ip=0.0.0.0  &>/dev/null &" >>~/.bashrc
RUN echo -e "echo \"\n😻🙀 Developer Enviroment\"\n" >>~/.bashrc 
RUN echo -e "sleep 1" >>~/.bashrc 
RUN echo -e "echo \"\n📺 You can open Jupyter Lab using the next URL:\n\"" >>~/.bashrc 
RUN echo -e "jupyter notebook list | egrep -o 'http://[^ ]+'" >>~/.bashrc 


